### ISSUE TITLE
IKVM.Runtime.InternalException : Could not load libjvm

### ISSUE THREAD

**Issue by san-coder1** [sergey-tihon/Stanford.NLP.NET#135]
### Discussed in https://github.com/sergey-tihon/Stanford.NLP.NET/discussions/134

<div type='discussions-op-text'>

<sup>Originally posted by **san-coder1** September 16, 2024</sup>
It works perfectly fine on my local Windows OS (64bit) machine. However, I am running my application from Azure Functions. 
In the Azure function runtime, I can see it has build the .dll and placed it in the bin folder.
![image](https://github.com/user-attachments/assets/51588730-a84a-4ffd-a85d-52dea4775bae)
I also confirmed that `Assembly.LoadFile(modelsAssemblyPath);` successfully loads the dll. 

It fails with following error when instantiating the StanfordCoreNLP class at
`var pipeline = new StanfordCoreNLP(props);`
```
System.TypeInitializationException : The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException : The type initializer for '<Module>' threw an exception. ---> System.TypeInitializationException : The type initializer for 'IKVM.Runtime.LibJava' threw an exception. ---> System.TypeInitializationException : The type initializer for 'IKVM.Runtime.LibJvm' threw an exception. ---> IKVM.Runtime.InternalException : Could not load libjvm.
   at IKVM.Runtime.LibJvm..ctor()
   at IKVM.Runtime.LibJvm..cctor()
   End of inner exception
   at IKVM.Runtime.LibJava..ctor()
   at IKVM.Runtime.LibJava..cctor()
   End of inner exception
   at IKVM.Runtime.BootstrapClassLoader..ctor(RuntimeContext context)
   at IKVM.Runtime.RuntimeClassLoaderFactory.GetBootstrapClassLoader()
   at IKVM.Runtime.RuntimeClassLoaderFactory.GetClassLoaderWrapper(ClassLoader javaClassLoader)
   at IKVM.Runtime.JNI.JNIFrame.GetFuncPtr(Object callerID,String clazz,String name,String sig)
   at java.lang.System.initProperties(Properties props)
   at java.lang.System.initializeSystemClass()
   at __<MethodAccessor>__System__initializeSystemClass()
   at IKVM.Runtime.Accessors.Java.Lang.SystemAccessor.InvokeInitializeSystemClass()
   at IKVM.Runtime.JVM.Init()
   at IKVM.Runtime.RuntimeInit.Init()
   at .cctor()
   End of inner exception
   at ikvm.runtime.Startup.init()
   at .cctor()
   End of inner exception
```
I also tried to set ikvm.home.root and ikvm.home, but that did not work either.
![image](https://github.com/user-attachments/assets/01b0c783-4ade-498f-b719-055a543fad46)
Any help would be greatly appreciated.
</div>

**Comment by san-coder1** [comment]
Created an issue with IKVM owners.
https://github.com/ikvmnet/ikvm/issues/598
