### ISSUE TITLE
Exception when running text annotation sample

### ISSUE THREAD

**Issue by gsscoder** [sergey-tihon/Stanford.NLP.NET#22]
When I try to run the sample from http://sergey-tihon.github.io/Stanford.NLP.NET/StanfordCoreNLP.html,
I got the following error in **FSharp Interactive**:

```PowerShell
--> Referenced 'E:\Temp\StanfNLP\packages\IKVM\lib\IKVM.OpenJDK.Core.dll'

--> Referenced 'E:\Temp\StanfNLP\packages\IKVM\lib\IKVM.OpenJDK.Util.dll'

--> Referenced 'E:\Temp\StanfNLP\packages\Stanford.NLP.CoreNLP\lib\stanford-corenlp-3.5.2.dll'

Adding annotator tokenize
TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
Adding annotator ssplit
Adding annotator pos
Binding session to 'E:\Temp\StanfNLP\packages\IKVM\lib\IKVM.OpenJDK.Util.dll'...
System.TypeInitializationException: The type initializer for 'edu.stanford.nlp.util.Timing' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'IKVM.OpenJDK.Text, Version=8.0.5449.1, Culture=neutral, PublicKeyToken=13235d27fcbfff58' or one of its dependencies. The system cannot find the file specified.
   at edu.stanford.nlp.util.Timing..cctor()
   --- End of inner exception stack trace ---
   at edu.stanford.nlp.util.Timing..ctor()
   at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(Properties config, DataInputStream rf, Boolean printLoading)
   at edu.stanford.nlp.tagger.maxent.MaxentTagger.readModelAndInit(Properties config, String modelFileOrUrl, Boolean printLoading)
   at edu.stanford.nlp.tagger.maxent.MaxentTagger..ctor(String modelFile, Properties config, Boolean printLoading)
   at edu.stanford.nlp.tagger.maxent.MaxentTagger..ctor(String modelFile)
   at edu.stanford.nlp.pipeline.POSTaggerAnnotator.loadModel(String , Boolean )
   at edu.stanford.nlp.pipeline.POSTaggerAnnotator..ctor(String annotatorName, Properties props)
   at edu.stanford.nlp.pipeline.AnnotatorImplementations.posTagger(Properties properties)
   at edu.stanford.nlp.pipeline.AnnotatorFactories.4.create()
   at edu.stanford.nlp.pipeline.AnnotatorPool.get(String name)
   at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(Properties , Boolean , AnnotatorImplementations )
   at edu.stanford.nlp.pipeline.StanfordCoreNLP..ctor(Properties props, Boolean enforceRequirements)
   at edu.stanford.nlp.pipeline.StanfordCoreNLP..ctor(Properties props)
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in E:\Temp\StanfNLP\annotation.fsx:line 25
Stopped due to error
```

I've downloaded packages with **Paket** and extracted the `models` dir from the `stanford-corenlp-3.5.2-models.jar`.

Am I missing something?

Thanks in advance.

**Comment by gsscoder** [comment]
I've put the sample inside an **F#** console application bound to runtime 3.1 (and before 4.0). This is the output before it crashes:
![stanford-nlp-dotnet_crash](https://cloud.githubusercontent.com/assets/1194228/9424606/4aef5e0e-48f2-11e5-9690-c2668303d225.png)
Hope it can help.
If need I post something, just ask me.

**Comment by gsscoder** [comment]
I asked help on S.O. and they helped. Hope this can help someone other too:
http://stackoverflow.com/questions/32163400/typeinitializationexception-when-running-stanford-nlp-corenlp-example.

Regards,
Giacomo
