### ISSUE TITLE
Issue on creating annotation on DateTime text Phase (e.g. last year)

### ISSUE THREAD

**Issue by xiaoyi78** [sergey-tihon/Stanford.NLP.NET#36]
Hi, 

I'm experiencing the issue on creating annotation on DateTime text phase, e.g. 'Last year'. It works for other text except any DateTime text phase.  The strange thing is it works under 'Debug' configuration, but not under 'Release' configuration. 

I'm using Stanford.NLP.CoreNLP 3.5.2 version. I appreciate if you could shed some light on this.

The error message is  below:  ( This error was reported in this web page by user Antonio de Perio as well: 
http://webcache.googleusercontent.com/search?q=cache:9v_lDNl4pkEJ:https://sergeytihon.wordpress.com/2013/10/26/stanford-corenlp-is-available-on-nuget-for-fc-devs/+&cd=3&hl=en&ct=clnk&gl=uk )

Provider com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl not found
IKVM.OpenJDK.XML.API
   at javax.xml.transform.FactoryFinder.newInstance(Class , String , ClassLoader , Boolean , Boolean )
   at javax.xml.transform.FactoryFinder.find(Class , String )
   at javax.xml.transform.TransformerFactory.newInstance()
   at edu.stanford.nlp.time.XMLUtils.printNode(OutputStream out, Node node, Boolean prettyPrint, Boolean includeXmlDeclaration)
   at edu.stanford.nlp.time.XMLUtils.nodeToString(Node node, Boolean prettyPrint)
   at edu.stanford.nlp.time.Timex.init(Element )
   at edu.stanford.nlp.time.Timex..ctor(Element element)
   at edu.stanford.nlp.time.Timex.fromMap(String text, Map map)
   at edu.stanford.nlp.time.TimeExpressionExtractorImpl.toCoreMaps(CoreMap , List , TimeIndex )
   at edu.stanford.nlp.time.TimeExpressionExtractorImpl.extractTimeExpressionCoreMaps(CoreMap annotation, String docDate, TimeIndex timeIndex)
   at edu.stanford.nlp.time.TimeAnnotator.annotate(Annotation annotation)
   at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(Annotation annotation)
   at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(Annotation annotation)
   at MyApp.NLP.StanfordExtractor.Annotate(String text) in C:\MyApp\Source\NLP\StanfordExtractor.cs:line 288
   at MyApp.NLP.StanfordExtractor.ExtractQueryTerms(String inputText) in C:\MyApp\Source\NLP\StanfordExtractor.cs:line 241
   at ConsoleApplication1.Program.Main(String[] args) in C:\Users\MyUser\Documents\Visual Studio 2015\Projects\NLP\ConsoleApplication1\Program.cs:line 17
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by sergey-tihon** [comment]
Close as an old issue
